# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 10"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: ""
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "assets/**/*"
    - "!assets/{img,js,scss}/**/*"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "assets/js/admin.js"

LOCAL_PATH: "http://courier.test"
